version: '3' 
services:
  host:
    image: clustershell:host
    build:
      context: .
      dockerfile: HostDockerfile
    container_name: host
    volumes: 
      - ./shared:/app/shared
    tty: true
  node1:
    image: clustershell:node1
    build: .
    container_name: node1
    environment:
      - NODE=node1
      - TEST=4
    volumes:
      - ./shared:/app/shared
    command: python node.py
  node2:
    image: clustershell:node2
    build: .
    container_name: node2
    environment:
      - NODE=node2
      - TEST=6
    volumes:
      - ./shared:/app/shared
    command: python node.py
  node3:
    image: clustershell:node3
    build: .
    container_name: node3
    environment:
      - NODE=node3
      - TEST=2
    volumes:
      - ./shared:/app/shared
    command: python node.py
  node4:
    image: clustershell:node4
    build: .
    container_name: node4
    environment:
      - NODE=node4
      - TEST=1
    volumes:
      - ./shared:/app/shared
    command: python node.py
